djl:
  # Define application type
  application-type: OBJECT_DETECTION
  # Define input data type, a model may accept multiple input data type
  input-class: ai.djl.modality.cv.Image
  # Define output data type, a model may generate different out put
  output-class: ai.djl.modality.cv.output.DetectedObjects
  #  output-class: ai.djl.modality.Classifications
  # Define filters that matches your application's need
  #  urls:
  #    - https://alpha-djl-demos.s3.amazonaws.com/model/quickdraw/doodle_mobilenet.zip
#  model-filter:
#    backbone: mobilenet
  # Override default pre-processing/post-processing behavior
  arguments:
    threshold: 0.2

server:
  port: 8082

